### ISSUE TITLE
Karte skaliert "falsch"

### ISSUE THREAD

**Issue by Elexil** [MeisterTR/ioB-scripts#1]
Hallo nochmal,

gibt es eine Möglichkeit die berechnete Karte zu skalieren?

Ich habe nur eingeschränkten Platz zur Anzeige der Map und meine aktuelle Konfiguration sieht wie folgt aus:

![image](https://user-images.githubusercontent.com/37534416/50592455-7c9b1e00-0e94-11e9-98d7-8120e8636aa2.png)

Die Karte ist aber um einiges größer. Das ist natürlich mehr als Suboptimal.

Kann man das im Script vielleicht steuern?

Danke und Gruß
Elexil

**Comment by MeisterTR** [comment]
andere mal zeile 99 in:
``setState("javascript.0.vis.RockroboMap", '<img src="' + canvas.toDataURL() + '" /style="width: auto ;height: 100%;">');``

**Comment by Elexil** [comment]
Ja super, das hat geklappt. Danke dir!
