### ISSUE TITLE
Error with Valetudo 0.3.0

### ISSUE THREAD

**Issue by vr6syncro** [MeisterTR/ioB-scripts#2]
`

host.ioBroker | 2019-04-06 19:16:13.741 | error | instance system.adapter.javascript.0 terminated with code 0 (OK)
-- | -- | -- | --
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at _combinedTickCallback (internal/process/next_tick.js:139:11)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at endReadableNT (_stream_readable.js:1064:12)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at IncomingMessage.emit (events.js:208:7)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at emitNone (events.js:111:20)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at setState (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at exports.XMLHttpRequest.dispatchEvent (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at exports.XMLHttpRequest.xmlHttp.onreadystatechange (script.js.User.Verschiedene.Cinderella_Livemap:36:13)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at updateMapPage (script.js.User.Verschiedene.Cinderella_Livemap:59:20)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: at getMapImageData (script.js.User.Verschiedene.Cinderella_Livemap:191:13)
host.ioBroker | 2019-04-06 19:16:13.740 | error | Caught by controller[0]: TypeError: Cannot read property 'forEach' of undefined

`

**Comment by MeisterTR** [comment]
done with  file: V3_X.js
