### ISSUE TITLE
v3_x Error

### ISSUE THREAD

**Issue by vr6syncro** [MeisterTR/ioB-scripts#3]
Hey,

ich bekomme error massages wenn ich das js ausführe:

```
javascript.0 | 2019-05-23 15:25:47.124 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
-- | -- | -- | --
javascript.0 | 2019-05-23 15:25:47.124 | error | at _combinedTickCallback (internal/process/next_tick.js:139:11)
javascript.0 | 2019-05-23 15:25:47.119 | error | at endReadableNT (_stream_readable.js:1064:12)
javascript.0 | 2019-05-23 15:25:47.119 | error | at IncomingMessage.emit (events.js:208:7)
javascript.0 | 2019-05-23 15:25:47.119 | error | at emitNone (events.js:111:20)
javascript.0 | 2019-05-23 15:25:47.119 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
javascript.0 | 2019-05-23 15:25:47.119 | error | at setState (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
javascript.0 | 2019-05-23 15:25:47.119 | error | at exports.XMLHttpRequest.dispatchEvent (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
javascript.0 | 2019-05-23 15:25:47.118 | error | at exports.XMLHttpRequest.xmlHttp.onreadystatechange (script.js.User.Verschiedene.Cinderella_Livemap:43:13)
javascript.0 | 2019-05-23 15:25:47.118 | error | at updateMapPage (script.js.User.Verschiedene.Cinderella_Livemap:101:43)
javascript.0 | 2019-05-23 15:25:47.118 | error | script.js.User.Verschiedene.Cinderella_Livemap: TypeError: Cannot read property '0' of undefined

```

der api pfad latest ist korrekt bei mir ich bekomme dort die daten.

**Comment by vr6syncro** [comment]
leider war es das nicht ganz:

`

11:03:26.770 | error | javascript.0 script.js.User.Verschiedene.Cinderella_Livemap: TypeError: Cannot read property '0' of undefined
-- | -- | --
11:03:26.771 | error | javascript.0 at updateMapPage (script.js.User.Verschiedene.Cinderella_Livemap:128:27)
11:03:26.771 | error | javascript.0 at exports.XMLHttpRequest.xmlHttp.onreadystatechange (script.js.User.Verschiedene.Cinderella_Livemap:56:13)

`

`

javascript.0 | 2019-05-24 11:03:26.571 | error | at process._tickCallback (internal/process/next_tick.js:181:9)
-- | -- | -- | --
javascript.0 | 2019-05-24 11:03:26.571 | error | at _combinedTickCallback (internal/process/next_tick.js:139:11)
javascript.0 | 2019-05-24 11:03:26.571 | error | at endReadableNT (_stream_readable.js:1064:12)
javascript.0 | 2019-05-24 11:03:26.571 | error | at IncomingMessage.emit (events.js:208:7)
javascript.0 | 2019-05-24 11:03:26.571 | error | at emitNone (events.js:111:20)
javascript.0 | 2019-05-24 11:03:26.571 | error | at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:447:13)
javascript.0 | 2019-05-24 11:03:26.571 | error | at setState (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:610:14)
javascript.0 | 2019-05-24 11:03:26.571 | error | at exports.XMLHttpRequest.dispatchEvent (/opt/iobroker/node_modules/iobroker.javascript/node_modules/xmlhttprequest/lib/XMLHttpRequest.js:591:25)
javascript.0 | 2019-05-24 11:03:26.570 | error | at exports.XMLHttpRequest.xmlHttp.onreadystatechange (script.js.User.Verschiedene.Cinderella_Livemap:56:13)
javascript.0 | 2019-05-24 11:03:26.565 | error | at updateMapPage (script.js.User.Verschiedene.Cinderella_Livemap:128:27)
javascript.0 | 2019-05-24 11:03:26.565 | error | script.js.User.Verschiedene.Cinderella_Livemap: TypeError: Cannot read property '0' of undefined

`

**Comment by MeisterTR** [comment]
probier nochmal

**Comment by vr6syncro** [comment]
Top! Sieht gut aus sollte klappen. Jedenfalls kommen keine Fehler mehr.
